spring:
  datasource:
    username: 'db_user'
    password: '8b3b91c7'
    url: 'jdbc:mysql://localhost:3306/assessment'



  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

    properties:
      hibernate:
        enable_lazy_load_no_trans: true
server:
  servlet:
    context-path: '/abc-hardware'
  port: 8989